format_version: 10
pipelines:
  control_plane:
    environment_variables:
      DEPLOYMENT: DEV
    materials:
      control_plane:
        mygit:
          git: https://github.com/deepesh-dev/simple-gradle.git
          branch: master
          includes:
            - README.md
    stages:
      stagebuild:
        clean_workspace: true
        jobs:
          buildtask:
            artiacts:
              type: build
              source: build/libs/*.jar
              destination: build/libs
            tasks:
              type : exec
              command: ./build.gradle