format_version: 10
pipelines:
  My_Gradle_Pipeline:
    group: sampleGradle
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-5d2f80d:
        git: https://github.com/deepesh-dev/simple-gradle.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - Build:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          build:
            timeout: 0
            tasks:
            - exec:
                command: ./build.gradle
                run_if: passed
